### ISSUE TITLE
no module named fused error

### ISSUE THREAD

**Issue by linghai06** [rosinality/stylegan2-pytorch#1]
Hi, I prepared the dataset and run the train.py as you said in the readme but got into a problem regrading the cpp extention.

`Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from model import Generator, Discriminator
  File "/data/llh/projects/stylegan2/model.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/data/llh/projects/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/data/llh/projects/stylegan2/op/fused_act.py", line 6, in <module>
    fused = load('fused', sources=['op/fused_bias_act.cpp', 'op/fused_bias_act_kernel.cu'])
  File "/home/llh/miniconda3/envs/py3pt11/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/home/llh/miniconda3/envs/py3pt11/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 824, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/llh/miniconda3/envs/py3pt11/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 967, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/llh/miniconda3/envs/py3pt11/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'
`

any idea?

**Comment by onion-liu** [comment]
Maybe you should try to update pytorch to 1.3, I have run the code successfully.

**Comment by linghai06** [comment]
> Maybe you should try to update pytorch to 1.3, I have run the code successfully.

thx! I update torch to v1.3.1. the module problem was solved but got another one:
`Traceback (most recent call last):
  File "train.py", line 375, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 145, in train
    fake_img, _ = generator(noise1)
  File "/home/llh/miniconda3/envs/py3pt13/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/llh/miniconda3/envs/py3pt13/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 442, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/llh/miniconda3/envs/py3pt13/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/llh/projects/stylegan2/model.py", line 447, in forward
    truncation_latent + truncation * (style - truncation_latent)
TypeError: sub(): argument 'other' (position 1) must be Tensor, not NoneType
`

I ran the code as it is. So how did you run the code successfully with the NoneType error?

**Comment by rosinality** [comment]
@linghai06 I have fixed it at 5f60e58a159349a222fac3ffcc3dd7246c03ed3d. Could you try newer version?

**Comment by linghai06** [comment]
@rosinality Sure. It works. Thank you!

**Comment by wrrogers** [comment]
I have the same issue.  I originally encountered on torch 1.4, I then downgraded to 1.3.1 but still have the problem.

**Comment by rosinality** [comment]
@wrrogers `ImportError: No module named 'fused'` errors?

**Comment by Young1403** [comment]
@rosinality Hi, I have the same problem with torch 1.4

Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from model import Generator, Discriminator
  File "E:\Gan\stylegan2-pytorch-master\model.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "E:\Gan\stylegan2-pytorch-master\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "E:\Gan\stylegan2-pytorch-master\op\fused_act.py", line 14, in <module>
    os.path.join(module_path, 'fused_bias_act_kernel.cu'),
  File "D:\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 682, in load
    is_python_module)
  File "D:\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 879, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1088, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "D:\Anaconda3\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'
Traceback (most recent call last):
  File "D:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\lib\site-packages\torch\distributed\launch.py", line 263, in <module>
    main()
  File "D:\Anaconda3\lib\site-packages\torch\distributed\launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['D:\\Anaconda3\\python.exe', '-u', 'train.py', '--local_rank=0', '--batch', '1', './lmdb']' returned non-zero exit status 1.

**Comment by rosinality** [comment]
@Young1403 Please check `os.path.join(tempfile.gettempdir(), 'torch_extensions', 'fused')` directories and extensions built without problem (it will be named like fused.so).

**Comment by zhanghp96** [comment]
@rosinality I have the same problem,  can you tell me how to solve it? thank you

Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from model import Encoder, Generator, Discriminator, CooccurDiscriminator
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/model.py", line 7, in <module>
    from stylegan2.model import (
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/model.py", line 11, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/op/fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 841, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1048, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/dh/anaconda3/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from model import Encoder, Generator, Discriminator, CooccurDiscriminator
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/model.py", line 7, in <module>
    from stylegan2.model import (
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/model.py", line 11, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/op/fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 841, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1048, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/dh/anaconda3/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from model import Encoder, Generator, Discriminator, CooccurDiscriminator
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/model.py", line 7, in <module>
    from stylegan2.model import (
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/model.py", line 11, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/op/fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 841, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1048, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/dh/anaconda3/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'
Traceback (most recent call last):
  File "train.py", line 21, in <module>
    from model import Encoder, Generator, Discriminator, CooccurDiscriminator
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/model.py", line 7, in <module>
    from stylegan2.model import (
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/model.py", line 11, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/dh/dh/swapping-autoencoder-pytorch-master/stylegan2/op/fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 841, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1048, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/dh/anaconda3/lib/python3.7/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'
Traceback (most recent call last):
  File "/home/dh/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dh/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/dh/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/dh/anaconda3/bin/python', '-u', 'train.py', '--local_rank=3', 'lmdb/']' returned non-zero exit status 1.

**Comment by rosinality** [comment]
@zhanghp96 First you need to check you can build custom extensions. (You can refer to this: https://github.com/pytorch/extension-cpp) Then you can clean /tmp/torch_extensions/fused and retry.

**Comment by zeta7337** [comment]
i have a same problem,torch 1.3.1,cuda10.1,what do you mean by "check you can build custom extensions"?can you explain in detail. thx
Traceback (most recent call last):
  File "generate.py", line 5, in <module>
    from model import Generator
  File "/data/zeta/zeta/model.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/data/zeta/zeta/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/data/zeta/zeta/op/fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 841, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1048, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/momobot/anaconda3/envs/train/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'

**Comment by rosinality** [comment]
@zeta7337 You can follow this https://pytorch.org/tutorials/advanced/cpp_extension.html or you can use this. https://github.com/rosinality/stylegan2-pytorch/issues/215#issuecomment-825649993

**Comment by hitxiaoting** [comment]
> i have a same problem,torch 1.3.1,cuda10.1,what do you mean by "check you can build custom extensions"?can you explain in detail. thx Traceback (most recent call last): File "generate.py", line 5, in from model import Generator File "/data/zeta/zeta/model.py", line 11, in from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d File "/data/zeta/zeta/op/**init**.py", line 1, in from .fused_act import FusedLeakyReLU, fused_leaky_relu File "/data/zeta/zeta/op/fused_act.py", line 15, in os.path.join(module_path, "fused_bias_act_kernel.cu"), File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 661, in load is_python_module) File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 841, in _jit_compile return _import_module_from_library(name, build_directory, is_python_module) File "/home/momobot/anaconda3/envs/train/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1048, in _import_module_from_library file, path, description = imp.find_module(module_name, [path]) File "/home/momobot/anaconda3/envs/train/lib/python3.6/imp.py", line 297, in find_module raise ImportError(_ERR_MSG.format(name), name=name) ImportError: No module named 'fused'

Hi, have you solved this issue? I have the same problem

**Comment by 1335001354** [comment]
@rosinality Hi, I have the same issue and my pytorch version is 1.3.1, here is the full message
C:\Users\dell\anaconda3\envs\torch_1.3\lib\site-packages\torchvision\io\..\video_reader\__init__.py
C:\Users\dell\anaconda3\envs\torch_1.3\lib\site-packages\torchvision\io\..\video_reader\__init__.pyc
C:\Users\dell\AppData\Local\Temp\torch_extensions\fused\fused\__init__.py
C:\Users\dell\AppData\Local\Temp\torch_extensions\fused\fused\__init__.pyc
(I try to print the path but the path is not found)
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    from invert import *
  File "E:\IDL\StyleCariGAN-master\invert.py", line 12, in <module>
    from exaggeration_model import StyleCariGAN
  File "E:\IDL\StyleCariGAN-master\exaggeration_model.py", line 7, in <module>
    from model import PixelNorm, EqualLinear, ConstantInput, StyledConv, ToRGB, ExaggerationLayer
  File "E:\IDL\StyleCariGAN-master\model.py", line 13, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "E:\IDL\StyleCariGAN-master\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "E:\IDL\StyleCariGAN-master\op\fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "C:\Users\dell\anaconda3\envs\torch_1.3\lib\site-packages\torch\utils\cpp_extension.py", line 661, in load
    is_python_module)
  File "C:\Users\dell\anaconda3\envs\torch_1.3\lib\site-packages\torch\utils\cpp_extension.py", line 841, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "C:\Users\dell\anaconda3\envs\torch_1.3\lib\site-packages\torch\utils\cpp_extension.py", line 1048, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "C:\Users\dell\anaconda3\envs\torch_1.3\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'fused'

**Comment by rosinality** [comment]
@1335001354 Have you tried to build custom extensions? Also pytorch version 1.3.1 seems bit low. I recommend pytorch 1.7.

**Comment by nobodypengium** [comment]
I try to run the code on 4 different environment.
Check ```~/.cache/torch_extensions/fused```:
**If success**, ```~/.cache/torch_extensions/fused``` will include
```build.ninja  fused_bias_act_kernel.cuda.o  fused_bias_act.o  fused.so```
**If faild**, ```~/.cache/torch_extensions/fused``` will include only
```build.ninja```

**Then, you can** go into ```~/.cache/torch_extensions/fused``` and run ```ninja```, ninja will try to build ```fused.so```, there will be errors (maybe include important things to solve this problem)
Maybe caused by ninja or gcc? I'm checking...

Update:
**(Passed)**: Environment 1 with gcc 7.5.0
**(Passed)**: Environment 2 with gcc 5.2.0
**(Failed)**: Environment 3 with gcc 9.4.0
```
/usr/local/cuda-9.0/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  119 | #error -- unsupported GNU version! gcc versions later than 6 are not supported!
      |  ^~~~~
ninja: build stopped: subcommand failed.
```
**(Failed)**: Environment 4 with gcc 4.9.3
```
 #error "You're running a too old version of GCC. We need GCC 5 or later."
```

Update:
**(Failed->Passed)**: Environment 3 with gcc 9.4.0 and g++ 5.5.0 -> gcc 5.5.0 and g++ 5.5.0

**Comment by keil555** [comment]
> **If success**, `~/.cache/torch_extensions/fused` will include `build.ninja fused_bias_act_kernel.cuda.o fused_bias_act.o fused.so` **If faild**, `~/.cache/torch_extensions/fused` will include only `build.ninja`
> 
> **Then, you can** go into `~/.cache/torch_extensions/fused` and run `ninja`, ninja will try to build `fused.so`, there will be errors (maybe include important things to solve this problem)

Thank you very much! You solved my problem perfectly!!!

**Comment by federicoromeo** [comment]
`ImportError: /home/federicor98/.cache/torch_extensions/py39_cu117/fused/fused.so: cannot open shared object file: No such file or directory`

When i inspect the folder "fused", in find only `build.ninja`  `fused_bias_act_kernel.cuda.o`

Then inside if i run ninja, i get:
>> ninja
[1/2] c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_...els/stylegan2/op/fused_bias_act.cpp -o fused_bias_act.o 
FAILED: fused_bias_act.o 
c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/federicor98/venv/lib/python3.9/site-packages/torch/include -isystem /home/federicor98/venv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/federicor98/venv/lib/python3.9/site-packages/torch/include/TH -isystem /home/federicor98/venv/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/federicor98/thesis/pretrained/encoder/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp -o fused_bias_act.o 
In file included from /home/federicor98/venv/lib/python3.9/site-packages/torch/include/torch/csrc/Device.h:4,
                 from /home/federicor98/venv/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                 from /home/federicor98/venv/lib/python3.9/site-packages/torch/include/torch/extension.h:6,
                 from /home/federicor98/thesis/pretrained/encoder/pixel2style2pixel/models/stylegan2/op/fused_bias_act.cpp:1:
/home/federicor98/venv/lib/python3.9/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
   12 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed

Any help?

**Comment by dinusha94** [comment]
> @zeta7337 You can follow this https://pytorch.org/tutorials/advanced/cpp_extension.html or you can use this. [#215 (comment)](https://github.com/rosinality/stylegan2-pytorch/issues/215#issuecomment-825649993)

manifest for nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04 not found: manifest unknown: manifest unknown, I get this error when trying #215 comment
